apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekV3TXpFeQpNakU1TVROYUZ3MDBNekV3TXpFeU1qRTVNVE5hTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDZ1MxelRHeG9VdXVHM3lwK3VwNGlDSXZSTUlzcmhHbHlkY3RaY25lQ0lBaTAxQndveAptNU0zdytGVTk2VDFNUitlWWRHZFNQa0FtUVRJVzFmcHJFWVpNb2lNdkdCOHVyL0Y3cG1GNkJoV0xSeG5NdVB2ClEybkhHSFVSQVlWbngwK1ArWmhmVmlEbURwWm9iK2dmRjFYNnFvTW5rbVVvc1E4QS9UcGxPRjJzMzdQR25zeU4KM1oxYjZEZGVyTW93NWpwVER0OVlYdHlhdUp5TU5TSWpaUTVTQ2k2S2JENmprVHFNbGFiL2tmbjJsb25nZ2w4OQoxaTBSbjkvamhxeFRscWtJSE5CUXp5R3ZkWStweDhyZW81ZmE1NTA1TmhCdWVTdG9IV1UrNXhRTnJjNStwbU83Ck4zNENyNjliRlArZkRvL1N5OENnSVMwdm1qZGV4ejZzOFhUTEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlQzQlBkcXJTVTBRT3pqU3Mrbgo3VjhCbGVGMVhqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFNdDVBNUFSKzFvN3kxSXQveWdLcEt3Qm9aQXBmCmNuQWFnTWlkVi9Mczd4TmgrK2YwODQrcWRmNFE3YjRqOTJldFFXSEdzbjMzTFRVS0hLWUt3MksxVjA0VjNpMEMKTVYxQ3pyWHdMbXd0OW40dm1DTC8yalY4QVNwbmtaV2YwN2lWR003bGJhZERVZ3ZDUWs2SzZLYjAwM0d3dUpPaApJaVh2RUs2bHIrV21uOHU4bURlSVJPUlJkODFlc3RYUHpjaFRRN2pBUWUrM2xWcVQzeitjZGNQM29QRXRIalA0CldueUJydm91R2luTDBEZFVPeGVJWHFlTjRDYzdxOGNQbnVHYkQxQUR2d0t3bjZYOXlObnQ5Sjd5T2Q3RGxwZHgKaGhBU0VPWWFXRXg1TnBZL3llY1BzS3FCU3Nia2N3QTRkS3BibTdBdkI4eEhRZktJWEE1d1JRakJSdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://a55e0ff6-83bd-492e-8157-1677e1ce3139.k8s.ondigitalocean.com
  name: do-ams3-k8s-training-test
contexts:
- context:
    cluster: do-ams3-k8s-training-test
    user: do-ams3-k8s-training-test-admin
  name: do-ams3-k8s-training-test
current-context: do-ams3-k8s-training-test
kind: Config
preferences: {}
users:
- name: do-ams3-k8s-training-test-admin
  user:
    token: dop_v1_32efcdac77e5fe6c5fc792390bc2ed15ef0000380361db461df5363df3ef730b
